newGame = document.querySelector('#newGame')
joinGameButton = document.querySelector('#joinGame')
title = document.querySelector('#title')
gameId = document.querySelector('#gameId')

createNewGame = ->
  if newGame.getAttribute('data-action') == 'cancel'
    TweenMax.to gameId, 0.4,
      ease: Sine.easeOut
      y: gameId.offsetHeight * 2
    TweenMax.to title.parentNode, 0.4,
      ease: Sine.easeOut
      height: title.parentNode.offsetHeight / 2
    newGame.innerText = 'Create Game'
    TweenMax.to title, 0.4,
      ease: Sine.easeIn
      y: -title.parentNode.offsetHeight
      onComplete: ->
        setTimeout (->
          title.querySelector('h2').innerText = 'Everyone is John'
          TweenMax.to title, 0.4,
            ease: Sine.easeOut
            y: 0
          TweenMax.set title.querySelector('h2'), 'padding-bottom': '0em'
          joinGameButton.setAttribute 'data-action', ''
          newGame.setAttribute 'data-action', ''
          return
        ), 150
        return
    return
  window.location = 'game/create'
  return

joinGame = ->
  if joinGameButton.getAttribute('data-action') == 'start'
    if gameId.value != ''
      window.location = 'game/' + gameId.value
    return
  TweenMax.to title, 0.4,
    ease: Sine.easeIn
    y: -title.parentNode.offsetHeight
    onComplete: ->
      setTimeout (->
        title.querySelector('h2').innerText = 'Enter Game ID'
        TweenMax.to title, 0.4,
          ease: Sine.easeOut
          y: 0
        TweenMax.to gameId, 0.4,
          ease: Sine.easeOut
          y: 0
        TweenMax.set title.querySelector('h2'), 'padding-bottom': '0.5em'
        TweenMax.to title.parentNode, 0.4,
          ease: Sine.easeOut
          height: title.parentNode.offsetHeight * 2
        newGame.innerText = 'Cancel'
        joinGameButton.setAttribute 'data-action', 'start'
        newGame.setAttribute 'data-action', 'cancel'
        return
      ), 250
      return
  return

document.addEventListener 'DOMContentLoaded', ->
  TweenMax.set title.parentNode, height: title.parentNode.offsetHeight / 2
  TweenMax.set gameId, y: gameId.offsetHeight
  return
newGame.addEventListener 'click', createNewGame
joinGameButton.addEventListener 'click', joinGame

# ---
# generated by js2coffee 2.1.0