// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET home page. */

  router.get('/game/create', function(req, res) {
    var id, length;
    length = 16;
    id = Math.round(Math.pow(36, length + 1) - (Math.random() * Math.pow(36, length))).toString(36).slice(1);
    return res.redirect(301, '/game/' + id);
  });

  router.get('/game/:id', function(req, res) {
    return res.render('game', {
      title: 'Everyone Is John'
    });
  });

  router.get('/game', function(req, res) {
    return res.redirect(301, '/');
  });

  router.get('/', function(req, res, next) {
    return res.render('index', {
      title: 'Everyone Is John'
    });
  });

  module.exports = router;

}).call(this);
